### PR TITLE
experimental: show color picker in advanced panel

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/webstudio-is/webstudio/issues/3399

Now users can tinker colors in css variables

Screenshot 2024-10-03 at 14 47 26

### CODE REVIEW

**Review by kof — APPROVED** [review]
looks like we can delete color-control now?

**Review by kof — CHANGES_REQUESTED** [review]
spacing seems broken 
image

**Comment by TrySound** [comment]
> looks like we can delete color-control now?

No, here I made advanced value an adaptive control. Color control restricts color only.

Works locally :)

image

**Comment by kof** [comment]
this component has size property with 2 versions, style panel in general uses a bigger one than advanced panel

**Comment by kof** [comment]
image
image

**Comment by kof** [comment]
in advanced, the picker button needs to be smaller, so that it has 2px margin

**Pull request closed without merging**
