### PR TITLE
feat: improve help widget with bug on hover effect

### PR DESCRIPTION
**Pull request by Venu005**
## Description
This pr is about improving the help widget by adding a hover effect on bug similar to help button.

## Code Review

- [ ] hi @kof, I need you to do
  -design and code review (feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)

### CODE REVIEW

**Comment by Venu005** [comment]
Can anyone help me by explaining why my pr is failing for Lost Pixel test.

**Comment by kof** [comment]
Hi, we were actually planing to move the bug button inside the help popover, so that its all in one and we only need 1 icon button in the builder

**Comment by kof** [comment]
fixed it here https://github.com/webstudio-is/webstudio/pull/3780

**Comment by kof** [comment]
thank you!

**Pull request closed without merging**
