### PR TITLE
feat: added navigator panel keyboard shortcut and refactored navigator docking behavior

### PR DESCRIPTION
**Pull request by kof**
## Description

With shortcuts, it became very clear that we need to make navigator closable even  when it is undocked, because a shortcut should't just stop working.

I had to refactor loading animation because to cover with overlay the panel it now need a different way of rendering the overlay. Instead of passing some CSS, I am now rendering an overlay above everything else.

## Steps for reproduction

1. Navigator should close/open using
  a) tab trigger
  b) close button in the panel
  c) keyboard shortcut (z)
2. It should behave the same  way in docked and undocked state, with only one difference: when undocked - it takes space in the layout, makes canvas smaller. Docked - it goes above.

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

**Review by johnsicili — CHANGES_REQUESTED** [review]
Issue: Add box, then add a heading (either via shortcuts or clicking). As soon as you add the child (heading), box is collapsed in the navigator.

On live, the box stays open so you can see what you're doing.

**Comment by kof** [comment]
@johnsicili fixed it, it was collapsing it without checking if undocked

**Comment by kof** [comment]
It should close when docked, but not touch it when undocked

**Comment by johnsicili** [comment]
@kof I'm still seeing it. Was this the issue you fixed?

https://github.com/user-attachments/assets/d979ae2a-3830-4e41-baba-c69f66b21caf

**Comment by kof** [comment]
@johnsicili great catch, didn't realize this one

**Review by johnsicili — APPROVED** [review]

**Review by TrySound — APPROVED** [review]

**Pull request merged**
