### PR TITLE
Generate preparsed tailwind theme

### PR DESCRIPTION
**Pull request by TrySound**
Here I replaced previous theming solution with generated code. It allows us to not have tailwind in dependencies and not bloat cli installation.

Additionally all values are preparsed into our internal format to avoid parsing at runtime when meta is imported and not have parsing dependencies like csstree (still there for now).

Cli install size

```diff
du -ck node_modules
- 57880
+ 42680
```

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
- [ ] hi @istarkov, I need you to do
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Review by istarkov — APPROVED** [review]

**Comment by kof** [comment]
It feels like we are ripe for a standalone tailwind package, does it still have much to do with radix?

**Comment by TrySound** [comment]
Right now it's the only place where tailwind is used. And it's just a theme, not actual generated tailwind. Nothing really to ship into separate project.

**Review by kof — APPROVED** [review]

**Comment by kof** [comment]
I didn't test, do we need extensive testing of radix components for this?

**Comment by TrySound** [comment]
I checked every component in storybook. All worked same as before.

**Pull request merged**
