### PR TITLE
feat: make loading screen background dark

### PR DESCRIPTION
**Pull request by kof**
## Description

A better looking loading screen

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 0000)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

**Comment by johnsicili** [comment]
Is there a way to combat this white screen? Even if its just setting the default color to the same of the loader, that will look better. White screen with nothing seems like there is some issue.

https://github.com/user-attachments/assets/f9a92055-5b48-4a40-acbf-ff1a7543c226

**Comment by kof** [comment]
done, check it out

**Comment by johnsicili** [comment]
Looks better. I don't know if its related to this PR, but when I access a Project via a share link, the loading screen doesn't go away

**Comment by kof** [comment]
reverted back the fix I was trying to make in parallel to the background change, which is about waiting for selected instance, before closing the overlay, currently its still having some movement after its loaded I wanted to avoid for a better effect, but seems too hard

@johnsicili good catch with this one

**Review by johnsicili — APPROVED** [review]

**Review by istarkov — APPROVED** [review]

**Pull request merged**
