### PR TITLE
feat: improve variable popover

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/webstudio-is/webstudio/issues/2532

Here changed variable popover UI

- removed save/cancel buttons - save is happening on close
- replaced value/resource tabs with type select
- support additional string, number and boolean values
- add validation to value and resource forms

Also added form utilities to manage and compose field validation.

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Comment by kof** [comment]
- [ ] JSON needs to be rendered all capital
image

**Comment by kof** [comment]
- [ ] I would expect it to save and close after typing value and hitting Enter, you?

image

**Comment by kof** [comment]
- [ ] I would expect the input for json value doesn't need quotes any more

image

**Comment by kof** [comment]
- [ ] in the list item says "object", but shouldn't it be also JSON? or both object? either way they should be the same, right?

image

**Comment by kof** [comment]
- [ ] when creating a variable and going right after type selector, it shows error on the name, though I wasn't adding name yet
image

**Review by kof — CHANGES_REQUESTED** [review]
ux improvements needed

**Comment by TrySound** [comment]
> when creating a variable and going right after type selector, it shows error on the name, though I wasn't adding name yet

You wanted name to be first focused field. You want it to be type now?

**Comment by TrySound** [comment]
> I would expect the input for json value doesn't need quotes any more

So empty object then?

**Comment by TrySound** [comment]
> in the list item says "object", but shouldn't it be also JSON? or both object? either way they should be the same, right?

So no need to distinct "array" and "object" there? Those are not selected types but compact value preview.

**Comment by kof** [comment]
> You wanted name to be first focused field. You want it to be type now?

No, name should be focused, but its weird when I click on type and get an error on name right away, seems like we need to check if user changed name or alternatively check if its empty and handle it separately

**Comment by kof** [comment]
> So empty object then?

Ideally just empty and not show error until its time to save

**Comment by kof** [comment]
> So no need to distinct "array" and "object" there? Those are not selected types but compact value preview.

Hmm, why do we have distinction between array and object there but not when creating the variable? I am surely missing something

**Comment by kof** [comment]
> but compact value preview.

What is a compact value preview? like instead of "{a: 1}" you write "object"? In that case why not represent both by JSON?

**Comment by kof** [comment]
Reg object/array vs JSON - its actually more correct to call it JSON, because its not a javascript object or array, its actually a JSON, right? meaning it can't have references or any other data structures, its a serializable object

**Comment by TrySound** [comment]
> No, name should be focused, but its weird when I click on type and get an error on name right away, seems like we need to check if user changed name or alternatively check if its empty and handle it separately

This is how every validation library works. Blur always triggers validation of the field.

**Comment by kof** [comment]
> This is how every validation library works. Blur always triggers validation of the field.

Alright, leave it for now as-is, it felt definitely weird to me, but maybe I am wrong

**Review by kof — APPROVED** [review]
looking great!

**Pull request merged**
