### PR TITLE
Preview on canvas when style panel select value is highlighted

### PR DESCRIPTION
**Pull request by kof**
https://github.com/webstudio-is/webstudio/issues/2324

https://github.com/webstudio-is/webstudio/assets/52824/7489689f-92bb-4cd5-888b-748bcae2369c

## Description

With this PR all select controls get a preivew when user hovers with the mouse or uses arrow keys.
We use select control in:
- position
- blend mode
- font-weight
- background size
- many others

In many cases preview won't be visible because cursor doesn't change unless you actually have mouse over that element

## Steps for reproduction

1. hover over position value
2. when mouse out preview should be gone
3. arrow keys do the same
4. if value wasn't applied and select box closed - preview should reset

## Code Review

- [ ] hi @TrySound , I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Review by TrySound — APPROVED** [review]

**Review by GoharAkram — APPROVED** [review]
- [ ] tested in blend and position settings as per instructions.. it works.

**Comment by kof** [comment]
Added font weight and background size previewing as well as these were separate code paths before.

**Comment by GoharAkram** [comment]
@kof Tested on font weight.. Works fine.

 What do you mean exactly by background size.. which section is this value in?

**Review by GoharAkram — APPROVED** [review]
- [ ] Tested on font weight and bg size.. it works fine

**Review by TrySound — APPROVED** [review]

**Pull request merged**
