### PR TITLE
refactor: enable isolated declarations in icons

### PR DESCRIPTION
**Pull request by TrySound**
Enforced isolated declarations which requires annotating all inputs and outputs for exports like flow enforced some time ago.

### CODE REVIEW

**Review by kof — APPROVED** [review]

**Comment by kof** [comment]
Just curious, what is this solving?

**Comment by TrySound** [comment]
In a long perspective typescript performance

**Comment by kof** [comment]
so that it doesn't have to analyze dependency graph if the export function has input/output typed? Is that already in-place?

**Comment by TrySound** [comment]
I guess so. Not sure how in practice but at least it will let us use oxc to generate typings instantly. Btw since all outputs will be defined we won't need to have fake declaration generation while typechecking to check schema edge cases. So typecheck will be faster.

**Review by istarkov — APPROVED** [review]

**Pull request merged**
