### PR TITLE
feat: switch props to binding popover

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/webstudio-is/webstudio/issues/2532

Here finally replaced variables panel with binding popover in all prop controls.
Additionally did better support of expressions in file and url controls.

The tricky part is managing expressions on control components level instead of global props panel level which gives us more granular control of behavior though requires more boilerplate code in each control.

There are still some bugs for example with loosing focus when start editing expression which I will fix in following validation fix.

## Testing
- check id in Body (string)
- aria-max something in Body (number)
- check "show" in body child (boolean)
- check href in Link (url)
- check src in Image (file)
- check state in Form (radio)
- check aria-autocomplete in body (select)
- check remove binding in resource fields

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Comment by kof** [comment]
- [ ] lets reduce the initial size of binding dots to 12px from 14 (looks a bit too massive right now), but add a 2px margin so that the hoverable surface is still quite big

**Comment by kof** [comment]
- [ ] bound show/id controls for example don't show as "bound" right now, is this on a todo?

**Comment by kof** [comment]
- [ ] I think its already reported in the main issue - binding select with a custom value shouldn't be posible

image

**Comment by kof** [comment]
- [ ] binding on a radio needs a better look, I think we discusssed it with taylor not sure if it was designed, his idea was to have a border around the radio items so that the binding button doesn't look so weird there

image

**Review by kof — APPROVED** [review]

**Comment by TrySound** [comment]
> bound show/id controls for example don't show as "bound" right now, is this on a todo?

Do you mean they are not disabled? They shouldn't because we want to control state with props to preview changes like error or success state in forms.

**Comment by kof** [comment]
> Do you mean they are not disabled? They shouldn't because we want to control state with props to preview changes like error or success state in forms.

I am confused, wasn't the plan for bound value to have a special state that is non-editable?

**Comment by TrySound** [comment]
We always supported editing single variable expression with props to preview features. So no it wasn't the plan to stop supporting it. We disabled only complex expression which cannot be reflected  in variable values.

**Pull request merged**
