### PR TITLE
feat: add variables to settings panel

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/webstudio-is/webstudio/issues/2532

Here integrated variables into props. Now it can be tested considering instances tree.

Screenshot 2023-11-06 at 13 10 33

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - test it on preview
- [ ] hi @kof, I need you to do
  - detailed review (read every line)

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Comment by kof** [comment]
- [ ] should we use `==` in expressions? I guess its a little more user friendly from high level, since we compare primitives there is probably no problem?

**Comment by kof** [comment]
- [ ] shouldn't we somehow allow the string value to be without quotes?

Screenshot 2023-11-06 at 11 17 33

**Comment by TrySound** [comment]
>  shouldn't we somehow allow the string value to be without quotes?

This is expression without dependencies. Can be any json-compatible type. Will add objects/arrays support later.

**Comment by TrySound** [comment]
> should we use == in expressions? I guess it's a little more user friendly from high level, since we compare primitives there is probably no problem?

both are supported

**Comment by kof** [comment]
> both are supported

I know, I think its better to show usage of == in our cases too, so when they look into how our components work, people are less confused about what === means

**Review by kof — APPROVED** [review]

**Pull request merged**
