### PR TITLE
feat: Allow seeing inspector in parallel with variable editor

### PR DESCRIPTION
**Pull request by kof**
When setting up a Resource variable, you want to see what data comes back instantly, seeing inspector comes in quite handy

## Code Review

- [ ] hi @istarkov , I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Comment by istarkov** [comment]
Resource payload does not change until you close the dialog

You can change URL and Click refresh this doesn't have any effect
image


image

**Comment by istarkov** [comment]
Would be good to have ability to switch between dialogs (dialog Im clicking become at front) as now they are something inbetween modal and non modal

image

**Review by istarkov — APPROVED** [review]
Refresh is not

**Comment by kof** [comment]
- resource not frefreshing is separate bug @TrySound said will fix
- switching between dialogs on click on my todo for the next pr
- resize/drag comming up next https://github.com/webstudio-is/webstudio/pull/3232

**Pull request merged**
