### PR TITLE
experimental: Download ssg

### PR DESCRIPTION
**Pull request by istarkov**
## Description

Can be broken as saas has other non rebased staging PRs

Additionally:
- [x] - Download will start even if dialog is closed

## Steps for reproduction

image

- [x] - Check that vanilla images has usual path
- [x] - Check that vercel has vercel.json at root and specific images paths
- [x] - Check that netlify has specific images paths

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

**Comment by TrySound** [comment]
I am wondering if we could export project with human readable filename?
> c6980944-1bda-4312-b1f6-cb0e377bfff1-FetP64Vvh4gG6CkP5Aaw5.zip

Maybe something like `kebabCase(project.title)`?

**Comment by kof** [comment]
- [ ] lets make the default destination vanilla?

**Comment by kof** [comment]
> I am wondering if we could export project with human readable filename?

Agree, would be much nicer

**Review by kof — APPROVED** [review]
approving, works great, but 2 little things need change

**Pull request merged**
