### PR TITLE
fix: show error on canvas when collection data is invalid

### PR DESCRIPTION
**Pull request by TrySound**
Fixes https://github.com/webstudio-is/webstudio/issues/3481 https://github.com/webstudio-is/webstudio/issues/3473

Screenshot 2024-06-04 at 12 54 22

### CODE REVIEW

**Comment by kof** [comment]
Lets think of a message that will tell them what to do or even link them to a document that explains it, this is going to be a major point of friction moving forward, lets try and help it as much as possible, @johnsicili please help us out here framing the message and potentially linking to something that's showing how to do it

**Comment by johnsicili** [comment]
Collection doc is live. 

Error suggestion:

Collection component requires an array in the data property. If binding external data, the array is nested somewhere within. [Learn more](https://docs.webstudio.is/university/core-components/collection.md#whats-an-array)

**Comment by kof** [comment]
@johnsicili great job on the doc, how about this text:

The Collection component requires an array in the data property. When binding external data, it is likely that the array is nested somewhere within, and you need to provide the correct path in the binding.

**Comment by johnsicili** [comment]
Works for me

**Comment by TrySound** [comment]
image

**Review by kof — APPROVED** [review]

**Pull request merged**
