### PR TITLE
NPM release flow

### PR DESCRIPTION
**Pull request by andrasbacsai**
Added the current release flow to the contribution guide.

### CODE REVIEW

**Review by kof — APPROVED** [review]
seems clear, will let others review too

**Review by okonet — APPROVED** [review]
It's clear to me but it lacks information about how to numb the version. I think we can live with this for now and introduce changesets and semantic versioning in the future. I can help with setting it up if you're interested.

**Comment by okonet** [comment]
Also the question is why is my PR failing on publish if I didn't change the version number. It should not try to publish it, correct?

**Review by rpominov — APPROVED** [review]

**Comment by andrasbacsai** [comment]
It will be changed to changeset, I just documented the current flow. 🙂

**Pull request merged**
