### PR TITLE
feat: add binding popover

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/webstudio-is/webstudio/issues/2532

Here added new binding popover as a replacement for variables popover. Integrated into resource fields and made button look like suggested by Mark and Taylor.

Screenshot 2023-12-30 at 13 26 12
Screenshot 2023-12-30 at 13 25 59

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Comment by kof** [comment]
- [ ] lets add a nice/soft transition for binding button see how it feels like in weblow
- [ ] isn't the new binding panel supposed to list all available variables?

**Review by kof — APPROVED** [review]

**Comment by kof** [comment]
@taylornowotny maybe you have an idea here, ofcourse popover on top of popover looks terrible

**Comment by kof** [comment]
One option could be positioning floating panels next to each other

**Comment by TrySound** [comment]
> isn't the new binding panel supposed to list all available variables?

It does

image

**Pull request merged**
