### PR TITLE
Add export dialog to publish

### PR DESCRIPTION
**Pull request by istarkov**
## Description

image

image

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Comment by GoharAkram** [comment]
- [ ] Image 1 looks perfect
- [ ] Image 2 edits:

Step 1:
1. Add full stop after package manager, but outside of link.
2. i think it is better to put "with a package manager" instead of "using a package manager"

Step 2:
1. Change "our" to "your"
2. Consider this v2: 

Run this command in your Terminal to install Webstudio CLI and sync your project.

or

Run this command in your Terminal to install Webstudio CLI and start syncing your project.

@kof

**Comment by istarkov** [comment]
Updated 
image

**Comment by istarkov** [comment]
Link colors changed
image

https://discord.com/channels/955905230107738152/1149380442315825212/1149408306671128666

**Comment by istarkov** [comment]
image

**Review by kof — APPROVED** [review]

**Pull request merged**
